### ISSUE TITLE
New release.

### ISSUE THREAD

**Issue by 46bit** [tokio-rs/tokio-timer#19]
Hi. The minor changes since `v0.1.0` are needed for me to release a crate, so I'd love it if you could make a new release. Cheers!

**Comment by carllerche** [comment]
Done. Thanks.

**Comment by 46bit** [comment]
@carllerche I think you forgot to publish to `crates.io`. :-(
